services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: taskroot
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672" # management UI

volumes:
  pgdata:
