spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: taskroot
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

  redis:
    host: localhost
    port: 6379
    timeout: 10s


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
